services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mov_play_db'
      - 'POSTGRES_PASSWORD=secretplay'
      - 'POSTGRES_USER=playuser'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: